name: Run Snowflake SQL Scripts

on:
  push:
    branches:
      - dev

jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Run SQL scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          for file in ./sql_scripts/*.sql; do
            echo "Running $file"
            python - <<EOF
import snowflake.connector

ctx = snowflake.connector.connect(
    user="${{ env.SNOWFLAKE_USER }}",
    password="${{ env.SNOWFLAKE_PASSWORD }}",
    account="${{ env.SNOWFLAKE_ACCOUNT }}",
    warehouse="${{ env.SNOWFLAKE_WAREHOUSE }}",
    database="${{ env.SNOWFLAKE_DATABASE }}",
    schema="${{ env.SNOWFLAKE_SCHEMA }}"
)

cs = ctx.cursor()
with open("$file", "r") as f:
    sql = f.read()
cs.execute(sql)
cs.close()
ctx.close()
EOF
    
